### ISSUE TITLE
Cannot stack up level

### ISSUE THREAD

**Issue by SonThanhVN** [cloudnode-pro/EnchantBookPlus#18]
im currently running a Minecraft server with 
Current: git-Purpur-2176 (MC: 1.20.4)*
i installed the plugins but when i try to combine two Sharpness level 5 book it come out still a Sharpness level 5 book
![image](https://github.com/user-attachments/assets/5704acb5-6c4f-4c79-ae07-3cc8a1dc877e)

i have not change anything in the config file from it default state

**Comment by zefir-git** [comment]
Hi! Do you have the `enchantbookplus.enchant.sharpness` or `enchantbookplus.enchant.*` permission? Can you please also send your plugin configuration

**Comment by SonThanhVN** [comment]
sorry for my late reply
i dont have any plugins to bind permission to player
and i dont see any errors or warnings in the console
i use the default configuration

**Comment by zefir-git** [comment]
The permissions are required to use the plugin.

**Comment by zefir-git** [comment]
I’m closing this issue as I didn’t get a response. The issue seems to be that you don’t have the required permissions. Please feel free to comment if you have any additional information to add, and I can reopen the issue if necessary. For new ideas or to report bugs, kindly open a new issue. Thank you!
